import { expect } from "../../expect.ts";
import type { Wat } from "../../wat.ts";
import type { CoreExpr } from "../ast.ts";
import { indent_lines } from "../emit/format.ts";
import type { CoreRuntimeBufferBuiltin } from "../runtime_buffer.ts";
import type {
  RuntimeTextEmitCtx,
  RuntimeTextHooks,
} from "../runtime_text/types.ts";
import { emit_runtime_buffer_allocation } from "./allocation.ts";
import {
  declare_runtime_float_format_locals,
  declare_runtime_integer_format_locals,
  runtime_float_format_plan,
  runtime_integer_format_plan,
} from "./plan.ts";

export function emit_runtime_integer_format<
  ctx extends RuntimeTextEmitCtx,
>(
  subject: CoreExpr,
  builtin: CoreRuntimeBufferBuiltin,
  ctx: ctx,
  hooks: Pick<RuntimeTextHooks<ctx>, "emit_expr">,
): Wat {
  let type: "i32" | "i64";

  if (builtin.name === "format_i32") {
    type = "i32";
  } else {
    expect(
      builtin.name === "format_i64",
      "Runtime integer formatting requires format_i32 or format_i64",
    );
    type = "i64";
  }

  const locals = runtime_integer_format_plan(type, ctx);
  declare_runtime_integer_format_locals(type, locals, ctx);
  const count_exit = "format_count_exit_" + locals.id.toString();
  const count_loop = "format_count_loop_" + locals.id.toString();
  const write_exit = "format_write_exit_" + locals.id.toString();
  const write_loop = "format_write_loop_" + locals.id.toString();
  const lines = [
    hooks.emit_expr(builtin.arg, ctx),
    "local.tee $" + locals.value,
    type + ".const 0",
    type + ".lt_s",
    "local.set $" + locals.negative,
    "local.get $" + locals.value,
    "local.set $" + locals.remaining,
    "local.get $" + locals.value,
    type + ".const 0",
    type + ".gt_s",
    "if",
    "  " + type + ".const 0",
    "  local.get $" + locals.value,
    "  " + type + ".sub",
    "  local.set $" + locals.remaining,
    "end",
    "i32.const 1",
    "local.set $" + locals.digit_count,
    "local.get $" + locals.remaining,
    "local.set $" + locals.quotient,
    "block $" + count_exit,
    "  loop $" + count_loop,
    "    local.get $" + locals.quotient,
    "    " + type + ".const -9",
    "    " + type + ".ge_s",
    "    br_if $" + count_exit,
    "    local.get $" + locals.quotient,
    "    " + type + ".const 10",
    "    " + type + ".div_s",
    "    local.set $" + locals.quotient,
    "    local.get $" + locals.digit_count,
    "    i32.const 1",
    "    i32.add",
    "    local.set $" + locals.digit_count,
    "    br $" + count_loop,
    "  end",
    "end",
    "local.get $" + locals.digit_count,
    "local.get $" + locals.negative,
    "i32.add",
    "local.set $" + locals.length,
    ...emit_runtime_buffer_allocation(
      subject,
      builtin,
      locals.length,
      locals.result,
      ctx,
    ),
    "local.get $" + locals.result,
    "local.get $" + locals.length,
    "i32.store",
    "local.get $" + locals.length,
    "local.set $" + locals.position,
    "block $" + write_exit,
    "  loop $" + write_loop,
    "    local.get $" + locals.remaining,
    "    " + type + ".const 10",
    "    " + type + ".div_s",
    "    local.set $" + locals.quotient,
    "    local.get $" + locals.position,
    "    i32.const 1",
    "    i32.sub",
    "    local.tee $" + locals.position,
    "    local.get $" + locals.result,
    "    i32.const 4",
    "    i32.add",
    "    i32.add",
    "    local.get $" + locals.quotient,
    "    " + type + ".const 10",
    "    " + type + ".mul",
    "    local.get $" + locals.remaining,
    "    " + type + ".sub",
    ...integer_digit_to_i32(type).map((line) => "    " + line),
    "    i32.const 48",
    "    i32.add",
    "    i32.store8",
    "    local.get $" + locals.quotient,
    "    local.tee $" + locals.remaining,
    "    " + type + ".eqz",
    "    br_if $" + write_exit,
    "    br $" + write_loop,
    "  end",
    "end",
    "local.get $" + locals.negative,
    "if",
    indent_lines(
      [
        "local.get $" + locals.result,
        "i32.const 4",
        "i32.add",
        "i32.const 45",
        "i32.store8",
      ].join("\n"),
      2,
    ),
    "end",
    "local.get $" + locals.result,
  ];
  return lines.join("\n");
}

export function emit_runtime_float_format<
  ctx extends RuntimeTextEmitCtx,
>(
  subject: CoreExpr,
  builtin: CoreRuntimeBufferBuiltin,
  ctx: ctx,
  hooks: Pick<RuntimeTextHooks<ctx>, "emit_expr">,
): Wat {
  expect(
    builtin.name === "format_f32",
    "Runtime float formatting requires format_f32",
  );
  expect(builtin.precision, "Runtime format_f32 precision is missing");
  const locals = runtime_float_format_plan(ctx);
  declare_runtime_float_format_locals(locals, ctx);
  const factor_exit = "format_f32_factor_exit_" + locals.id.toString();
  const factor_loop = "format_f32_factor_loop_" + locals.id.toString();
  const count_exit = "format_f32_count_exit_" + locals.id.toString();
  const count_loop = "format_f32_count_loop_" + locals.id.toString();
  const fraction_exit = "format_f32_fraction_exit_" + locals.id.toString();
  const fraction_loop = "format_f32_fraction_loop_" + locals.id.toString();
  const integer_exit = "format_f32_integer_exit_" + locals.id.toString();
  const integer_loop = "format_f32_integer_loop_" + locals.id.toString();
  const lines = [
    hooks.emit_expr(builtin.arg, ctx),
    "local.set $" + locals.value,
    hooks.emit_expr(builtin.precision, ctx),
    "local.set $" + locals.precision,
    "local.get $" + locals.precision,
    "i32.const 0",
    "i32.lt_s",
    "if",
    "  unreachable",
    "end",
    "local.get $" + locals.precision,
    "i32.const 6",
    "i32.gt_s",
    "if",
    "  unreachable",
    "end",
    "local.get $" + locals.value,
    "local.get $" + locals.value,
    "f32.ne",
    "if",
    "  unreachable",
    "end",
    "f32.const 1",
    "local.set $" + locals.factor_f32,
    "i64.const 1",
    "local.set $" + locals.factor_i64,
    "i32.const 0",
    "local.set $" + locals.digit_count,
    "block $" + factor_exit,
    "  loop $" + factor_loop,
    "    local.get $" + locals.digit_count,
    "    local.get $" + locals.precision,
    "    i32.ge_s",
    "    br_if $" + factor_exit,
    "    local.get $" + locals.factor_f32,
    "    f32.const 10",
    "    f32.mul",
    "    local.set $" + locals.factor_f32,
    "    local.get $" + locals.factor_i64,
    "    i64.const 10",
    "    i64.mul",
    "    local.set $" + locals.factor_i64,
    "    local.get $" + locals.digit_count,
    "    i32.const 1",
    "    i32.add",
    "    local.set $" + locals.digit_count,
    "    br $" + factor_loop,
    "  end",
    "end",
    "local.get $" + locals.value,
    "f32.const 0",
    "f32.lt",
    "local.set $" + locals.negative,
    "local.get $" + locals.negative,
    "if (result f32)",
    "  f32.const 0",
    "  local.get $" + locals.value,
    "  f32.sub",
    "else",
    "  local.get $" + locals.value,
    "end",
    "local.set $" + locals.magnitude,
    "local.get $" + locals.magnitude,
    "local.get $" + locals.factor_f32,
    "f32.mul",
    "f32.const 0.5",
    "f32.add",
    "f32.const 9.223372e18",
    "f32.lt",
    "if",
    "else",
    "  unreachable",
    "end",
    "local.get $" + locals.magnitude,
    "local.get $" + locals.factor_f32,
    "f32.mul",
    "f32.const 0.5",
    "f32.add",
    "i64.trunc_f32_s",
    "local.set $" + locals.scaled,
    "local.get $" + locals.scaled,
    "local.get $" + locals.factor_i64,
    "i64.div_s",
    "local.set $" + locals.integer,
    "local.get $" + locals.scaled,
    "local.get $" + locals.factor_i64,
    "i64.rem_s",
    "local.set $" + locals.fraction,
    "i32.const 1",
    "local.set $" + locals.digit_count,
    "local.get $" + locals.integer,
    "local.set $" + locals.quotient,
    "block $" + count_exit,
    "  loop $" + count_loop,
    "    local.get $" + locals.quotient,
    "    i64.const 10",
    "    i64.lt_s",
    "    br_if $" + count_exit,
    "    local.get $" + locals.quotient,
    "    i64.const 10",
    "    i64.div_s",
    "    local.set $" + locals.quotient,
    "    local.get $" + locals.digit_count,
    "    i32.const 1",
    "    i32.add",
    "    local.set $" + locals.digit_count,
    "    br $" + count_loop,
    "  end",
    "end",
    "local.get $" + locals.digit_count,
    "local.get $" + locals.negative,
    "i32.add",
    "local.get $" + locals.precision,
    "i32.add",
    "local.set $" + locals.length,
    "local.get $" + locals.precision,
    "i32.eqz",
    "if",
    "else",
    "  local.get $" + locals.length,
    "  i32.const 1",
    "  i32.add",
    "  local.set $" + locals.length,
    "end",
    ...emit_runtime_buffer_allocation(
      subject,
      builtin,
      locals.length,
      locals.result,
      ctx,
    ),
    "local.get $" + locals.result,
    "local.get $" + locals.length,
    "i32.store",
    "local.get $" + locals.length,
    "local.set $" + locals.position,
    "i32.const 0",
    "local.set $" + locals.digit_count,
    "block $" + fraction_exit,
    "  loop $" + fraction_loop,
    "    local.get $" + locals.digit_count,
    "    local.get $" + locals.precision,
    "    i32.ge_s",
    "    br_if $" + fraction_exit,
    "    local.get $" + locals.fraction,
    "    i64.const 10",
    "    i64.div_s",
    "    local.set $" + locals.quotient,
    "    local.get $" + locals.position,
    "    i32.const 1",
    "    i32.sub",
    "    local.tee $" + locals.position,
    "    local.get $" + locals.result,
    "    i32.const 4",
    "    i32.add",
    "    i32.add",
    "    local.get $" + locals.fraction,
    "    local.get $" + locals.quotient,
    "    i64.const 10",
    "    i64.mul",
    "    i64.sub",
    "    i32.wrap_i64",
    "    i32.const 48",
    "    i32.add",
    "    i32.store8",
    "    local.get $" + locals.quotient,
    "    local.set $" + locals.fraction,
    "    local.get $" + locals.digit_count,
    "    i32.const 1",
    "    i32.add",
    "    local.set $" + locals.digit_count,
    "    br $" + fraction_loop,
    "  end",
    "end",
    "local.get $" + locals.precision,
    "i32.eqz",
    "if",
    "else",
    "  local.get $" + locals.position,
    "  i32.const 1",
    "  i32.sub",
    "  local.tee $" + locals.position,
    "  local.get $" + locals.result,
    "  i32.const 4",
    "  i32.add",
    "  i32.add",
    "  i32.const 46",
    "  i32.store8",
    "end",
    "local.get $" + locals.integer,
    "local.set $" + locals.fraction,
    "block $" + integer_exit,
    "  loop $" + integer_loop,
    "    local.get $" + locals.fraction,
    "    i64.const 10",
    "    i64.div_s",
    "    local.set $" + locals.quotient,
    "    local.get $" + locals.position,
    "    i32.const 1",
    "    i32.sub",
    "    local.tee $" + locals.position,
    "    local.get $" + locals.result,
    "    i32.const 4",
    "    i32.add",
    "    i32.add",
    "    local.get $" + locals.fraction,
    "    local.get $" + locals.quotient,
    "    i64.const 10",
    "    i64.mul",
    "    i64.sub",
    "    i32.wrap_i64",
    "    i32.const 48",
    "    i32.add",
    "    i32.store8",
    "    local.get $" + locals.quotient,
    "    local.tee $" + locals.fraction,
    "    i64.eqz",
    "    br_if $" + integer_exit,
    "    br $" + integer_loop,
    "  end",
    "end",
    "local.get $" + locals.negative,
    "if",
    "  local.get $" + locals.result,
    "  i32.const 4",
    "  i32.add",
    "  i32.const 45",
    "  i32.store8",
    "end",
    "local.get $" + locals.result,
  ];
  return lines.join("\n");
}

function integer_digit_to_i32(type: "i32" | "i64"): string[] {
  if (type === "i64") {
    return ["i32.wrap_i64"];
  }

  return [];
}
