import type { Func } from "../mod.ts";

export const allocator_alloc = "__alloc";
export const allocator_free = "__free";
export const allocator_free_head = "__free_head";

export function emit_persistent_alloc(size: string, alignment: 4 | 8): string {
  return size + "\ni32.const " + alignment.toString() + "\ncall $__alloc";
}

export function runtime_allocator_funcs(): Record<string, Func> {
  return {
    [allocator_alloc]: {
      name: allocator_alloc,
      params: [
        { name: "size", type: "i32" },
        { name: "alignment", type: "i32" },
      ],
      result: "i32",
      body: [
        "(local $needed i32)",
        "(local $prev i32)",
        "(local $block i32)",
        "(local $end i32)",
        "local.get $size",
        "i32.const 7",
        "i32.add",
        "i32.const -8",
        "i32.and",
        "i32.const 8",
        "i32.add",
        "local.set $needed",
        "global.get $__free_head",
        "local.set $block",
        "block $not_found",
        "  loop $search",
        "    local.get $block",
        "    i32.eqz",
        "    br_if $not_found",
        "    local.get $block",
        "    i32.load",
        "    local.get $needed",
        "    i32.ge_u",
        "    if",
        "      local.get $prev",
        "      i32.eqz",
        "      if",
        "        local.get $block",
        "        i32.load offset=4",
        "        global.set $__free_head",
        "      else",
        "        local.get $prev",
        "        local.get $block",
        "        i32.load offset=4",
        "        i32.store offset=4",
        "      end",
        "      local.get $block",
        "      i32.const 8",
        "      i32.add",
        "      return",
        "    end",
        "    local.get $block",
        "    local.set $prev",
        "    local.get $block",
        "    i32.load offset=4",
        "    local.set $block",
        "    br $search",
        "  end",
        "end",
        "global.get $__closure_heap",
        "local.tee $block",
        "local.get $needed",
        "i32.add",
        "local.tee $end",
        "memory.size",
        "i32.const 16",
        "i32.shl",
        "i32.gt_u",
        "if",
        "  local.get $end",
        "  memory.size",
        "  i32.const 16",
        "  i32.shl",
        "  i32.sub",
        "  i32.const 65535",
        "  i32.add",
        "  i32.const 16",
        "  i32.shr_u",
        "  memory.grow",
        "  i32.const -1",
        "  i32.eq",
        "  if",
        "    unreachable",
        "  end",
        "end",
        "local.get $block",
        "local.get $needed",
        "i32.store",
        "local.get $end",
        "global.set $__closure_heap",
        "local.get $block",
        "i32.const 8",
        "i32.add",
      ].join("\n"),
    },
    [allocator_free]: {
      name: allocator_free,
      params: [{ name: "ptr", type: "i32" }],
      result: "i32",
      body: [
        "local.get $ptr",
        "i32.eqz",
        "if",
        "  i32.const 0",
        "  return",
        "end",
        "local.get $ptr",
        "i32.const 8",
        "i32.sub",
        "local.tee $ptr",
        "global.get $__free_head",
        "i32.store offset=4",
        "local.get $ptr",
        "global.set $__free_head",
        "local.get $ptr",
        "i32.const 8",
        "i32.add",
      ].join("\n"),
    },
  };
}
