name: pr

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: install wabt
        run: |
          sudo apt-get update
          sudo apt-get install -y wabt

      - name: format
        run: deno fmt --check *.ts src .github/workflows/*.yaml

      - name: lint
        run: deno lint

      - name: run tests
        run: deno test --allow-read --allow-write --allow-run
